In [3]:
import array as myarray

In [9]:
arr = myarray.array('i', [1,2,3,4])
arr1 = myarray.array('d' , [1.2,3.3,334.5])
arr2 = myarray.array('u' , ['h','y'])

In [11]:
print(arr.typecode)
print(arr1.typecode)

i
d


In [14]:
print(arr)
print(arr1)
print(arr2)

array('i', [1, 2, 3, 4])
array('d', [1.2, 3.3, 334.5])
array('u', 'hy')


In [16]:
print(len(arr1))
print(len(arr2))
print(len(arr))

3
2
4


In [27]:
for i in range(0,len(arr)):
    print(arr[i],end=" ")
print("\n")
for i in range(0,len(arr1)):
    print(arr1[i],end=" ")
print("\n")
for i in range(len(arr2)):
    print(arr2[i],end=" ")
print("\n")

1 2 3 4 

1.2 3.3 334.5 

h y 



In [31]:
x = list(range(1,100,2))
new_array=myarray.array('i' , x)

In [32]:
for i in range(len(new_array)):
    print(new_array[i],end = " ")
print("\n")

1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99 



In [47]:
new_arr = myarray.array("i" , [3,4,5,6,7,8,9])
for i in range(len(new_arr)):
    print(new_arr[i],end=" ")
print(end="\n")
new_arr.insert(0,2)
new_arr.insert(0,1)
for i in range(len(new_arr)):
    print(new_arr[i], end=" ")
print(end= "\n")


3 4 5 6 7 8 9 
1 2 3 4 5 6 7 8 9 


In [43]:
new_arr

array('i', [1, 2, 2, 1, 3, 4, 5, 6, 7, 8, 9])

In [48]:
new_array = myarray.array("i", [1,2,2,4,5])
for i in range(len(new_array)):
    print(new_array[i],end=" ")
print(end="\n")

1 2 2 4 5 


In [49]:
new_array[2] = 3
for i in range(len(new_array)):
    print(new_array[i],end=" ")
print(end="\n")

1 2 3 4 5 


In [51]:
new_array.pop(2)
for i in range(len(new_array)):
    print(new_array[i],end=" ")
print(end="\n")

1 2 5 


In [62]:
x = list(range(0,100,3))
arr = myarray.array("i",x)
arr0 = arr[10:20]
for i in range(0,len(arr0)):
    print(arr0[i],end=" ")
print("\n")
arr1 = arr[10:-10]
for i in range(0,len(arr1)):
    print(arr1[i],end=" ")
print("\n")
arr2 = arr[::-1]
for i in range(0,len(arr2)):
    print(arr2[i],end=" ")
print("\n")

30 33 36 39 42 45 48 51 54 57 

30 33 36 39 42 45 48 51 54 57 60 63 66 69 

99 96 93 90 87 84 81 78 75 72 69 66 63 60 57 54 51 48 45 42 39 36 33 30 27 24 21 18 15 12 9 6 3 0 



In [65]:
x = list(range(0,1000000,2))
search_array = myarray.array("i" , x)
for i in range(len(search_array[0:10])):
    print(search_array[i],end=" ")
print("\n")

0 2 4 6 8 10 12 14 16 18 



In [66]:
index = search_array.index(10002)
res = search_array[index]
print(index,res)

5001 10002


In [69]:
sort_array=myarray.array('i' ,[5,6,7,1,2,4,8])
sorted_array = sort_array.tolist()
sorted_array.sort()
print(sorted_array)
sorted_array.sort(reverse=True)
print(sorted_array)

[1, 2, 4, 5, 6, 7, 8]
[8, 7, 6, 5, 4, 2, 1]


In [70]:
import numpy as np

In [71]:
arr = np.array([1,2,3,4,5])

In [72]:
arr

array([1, 2, 3, 4, 5])

In [79]:
zeros = np.zeros((2,2))
ones = np.ones((2,2))
const = np.full((3,3),5)
iden = np.eye(3)

In [80]:
print(zeros)
print(ones)
print(const)
print(iden)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [81]:
random=np.random.random((2,2))

In [82]:
random

array([[0.53718077, 0.90889418],
       [0.09358637, 0.63106307]])

In [83]:
oned = np.array(1)

In [84]:
oned

array(1)

In [85]:
x = np.array([[1,2,3,4,445],[2,3,4,4,5]])

In [86]:
x

array([[  1,   2,   3,   4, 445],
       [  2,   3,   4,   4,   5]])

In [90]:
a = np.array([[1,2,3,4]], dtype=np.int64)
b = np.array([[1,2,3,4]], dtype=np.int64)
addition = np.add(a,b)
print(addition)

[[2 4 6 8]]


In [97]:
x = list(range(10))
arr =myarray.array("i", x)
for i in range(len(arr)):
    print(arr[i],end= " ")
print(end="\n")
arr.insert(0,1)

0 1 2 3 4 5 6 7 8 9 


In [107]:
x = list(range(0,100000,2))
arry = myarray.array("i",x)
for i in range(len(arry[10:10])):
    print(arry[i],end= " ")
print("\n")


In [6]:
r_nums = int(input("enter the rows"))
c_nums = int(input("enter the cols"))
twod_arr = [(0 for col in range(c_nums) for row in range(r_nums))]

for row in range(r_nums):
    for col in range(c_nums):
        twod_arr[row][col]= row*col
print(twod_arr)

enter the rows2
enter the cols3


TypeError: 'generator' object does not support item assignment

In [7]:
r_num = int(input("enter the rows"))
c_num = int(input("enter the cols"))
twod_arr = [[0 for col in range(c_nums)] for row in range(r_nums)]

for row in range(r_nums):
    for col in range(c_nums):
        twod_arr[row][col]= row*col
print(twod_arr)

enter the rows2
enter the cols3
[[0, 0, 0], [0, 1, 2]]


In [13]:
n_rows = int(input("enter the rows"))
n_cols = int(input("enter the cols"))
two_d = [[0 for col in range(n_cols)] for row in range(n_rows)]

for row in range(n_rows):
    for col in range(n_cols):
        two_d[row][col]=row*col
    print(two_d)

enter the rows2
enter the cols3
[[0, 0, 0], [0, 0, 0]]
[[0, 0, 0], [0, 1, 2]]
